---
- name: set up login messages
  hosts: all
  collections:
  - fvzwieten.loginmsg
  become: yes
  tasks:
  - name: put a logon message before logging in
    loginmsg:
      text: Hello, you are entering a Hackathon Machine!
      when: before
      fqdn: true
      state: present

  - name: put a logon message before logging in
    loginmsg:
      text: Hi there, welcome in a Hackathon Machine!
      when: after
      fqdn: true
